# @format

version: '3.5'

services:
  react:
    build:
      context: .
    environment:
      - CHOKIDAR_USEPOLLING=true
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - '1234:1234'
      - '1337:1337'
